### ISSUE TITLE
_goodix_irq_handler not declared error

### ISSUE THREAD

**Issue by sinafarhadiee** [ploys/arduino-goodix#7]
when i try to run it on my arduino mega my arduino show 
////////////////////////////////////////////////////////////////////
C:\Users\sa\Documents\arduino\libraries\arduino-goodix-master\Goodix.cpp: In member function 'void Goodix::armIRQ()':

C:\Users\sa\Documents\arduino\libraries\arduino-goodix-master\Goodix.cpp:150:27: error: '_goodix_irq_handler' was not declared in this scope

   attachInterrupt(intPin, _goodix_irq_handler, RISING);
/////////////////////////////////////////////////////////////////////
how can i fix it?
thank you;

**Comment by nik-sharky** [comment]
Hi, maybe on arduino there is no ICACHE_RAM_ATTR macro, initially library was developed for ESP8266.
Try to define macro in code or remove it from Goodix.cpp.

**Comment by momosh13** [comment]
Hello,
The issue was not resolved for DUE even if I remove ICACHE_RAM_ATTR macro

//void ICACHE_RAM_ATTR _goodix_irq_handler() {
//  noInterrupts();
//  goodixIRQ = 1;
//  interrupts();
//}

I'm getting different error after that.

WARNING: Category 'Touch' in library GT911 is not valid. Setting to 'Uncategorized'
libraries\goodix-master\Goodix.cpp.o: In function `__disable_irq':

C:\Users\HPVIDEO\Documents\Arduino\libraries\arduino-logger-master\src/log.h:9: multiple definition of `_log_printf(char const*, ...)'

sketch\GT911_touch.ino.cpp.o:C:\Users\HPVIDEO\Documents\Arduino\libraries\arduino-logger-master\src/log.h:9: first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino Due (Programming Port).

Looking for help.
Thanks.

**Comment by hadiinfo** [comment]
Hi all, 

 did you find a solution for this to compile? Please share your experience as it will be really helpful here. 

Thank you

**Comment by nik-sharky** [comment]
Hi all,
I add 
#ifndef ICACHE_RAM_ATTR
#define ICACHE_RAM_ATTR
#endif

to Goodix.cpp, it should help on non esp boards.

**Comment by hadiinfo** [comment]
Really appreciate it! It works now!!

**Comment by hadiinfo** [comment]
just as a side note, my pull up resistors were not appropriate so I had to lower the serial speed to 9600

**Comment by nik-sharky** [comment]
Fixed
